version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: check-fk-missing-index

    stdin_open: true

    volumes:
      - .:/app

    working_dir: /app

  db:
    image: postgres

    environment:
      POSTGRES_PASSWORD: test
